FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY scripts/ ./scripts/
COPY sql/ ./sql/
COPY frontend/ ./frontend/

WORKDIR /app/scripts

EXPOSE 8000

CMD ["uvicorn", "api_prediccion:app", "--host", "0.0.0.0", "--port", "8000"]
